import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <header>
                <nav style={{textAlign:"center"}}>
                    <div>
                        <h1>LOGO</h1>
                    </div>
                    <div>
                        <Link href="/">HOME</Link>
                        &nbsp;|&nbsp;
                        <Link href="/about">ABOUT</Link>
                        &nbsp;|&nbsp;
                        <Link href="/dashboard">DASHBOARD</Link>
                    </div>
                    
                </nav>
            </header>
            <hr/>
            <div>
                {children}
            </div>
            <hr/>
            <footer style={{textAlign:"center"}}>
                <Link href="/legal/terms">Terms</Link>
                &nbsp;|&nbsp;
                <Link href="/legal/privacy">Privacy</Link>
            </footer>
        </body>
    </html>
  )
}
