import Link from "next/link";

export default function Terms() {
  return (
    <div>
        <h1>TERMS</h1>
        <p>
            Et semper purus ultricies laoreet. Nulla posuere nisi vitae turpis varius, imperdiet ultrices turpis facilisis. Donec felis massa, laoreet sed neque id, malesuada convallis sapien. Nullam congue enim eget lacinia vulputate. Morbi accumsan augue vitae ex bibendum, id venenatis tortor venenatis. Nam nec venenatis elit, in viverra orci. In purus metus, iaculis quis turpis quis, pulvinar vehicula mauris. Etiam nulla leo, volutpat eu risus a, facilisis elementum massa. Phasellus id posuere augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent maximus dignissim vestibulum. Aliquam ullamcorper tellus eu quam posuere, sed dapibus erat commodo. Nullam elementum eu ante vel hendrerit. Aenean placerat lacus at lorem laoreet malesuada. Phasellus vitae leo id risus ultricies semper.
            Donec interdum ipsum diam, ut hendrerit mi vehicula non. Vivamus quam arcu, dignissim quis nisl non, vestibulum rutrum tellus. Quisque sed eros arcu. Aliquam viverra non enim et volutpat. Praesent neque mauris, blandit vitae libero et, fringilla finibus metus. Nunc interdum, tortor ut tempus hendrerit, libero elit convallis augue, sit amet viverra leo orci nec arcu. Morbi porttitor ligula est, id sagittis magna posuere at. Mauris aliquet turpis id diam rhoncus, quis euismod nulla vulputate. Fusce accumsan nunc purus, a rutrum purus rhoncus sed. Duis eu justo ornare, fermentum leo ut, rutrum mi. Nullam nec arcu vitae enim iaculis pulvinar in sit amet neque. In pretium lectus vel ipsum vehicula, in sodales purus viverra.
        </p>
        <p>
            Etiam at mattis urna. Vestibulum ut nulla leo. Donec pretium auctor euismod. Suspendisse tristique tortor non malesuada consequat. Nulla pellentesque eros mauris, non viverra mauris tempus nec. Cras id dapibus justo.
        </p>
        <p>
            Duis ut consequat mi, in bibendum lectus. Morbi cursus, risus vel aliquet sodales, velit nisi consequat nulla, nec faucibus nibh tellus at elit. Morbi commodo quam sapien, quis blandit diam aliquet eu. Phasellus nisl est, venenatis in nisl sit amet, commodo tempus velit. Maecenas at ipsum sodales, bibendum sem a, hendrerit orci. Cras viverra, dolor ac posuere auctor, nisl sapien commodo nunc, ac imperdiet nunc leo nec nunc. Nulla non dolor neque. Quisque sodales ipsum maximus mattis dapibus. Ut suscipit augue eget bibendum faucibus. Donec feugiat tempus suscipit. Donec eu justo odio. Vivamus vel nulla turpis. Aliquam eget justo magna. In sit amet dui id eros tincidunt sagittis ut in lorem. In pellentesque pharetra imperdiet.
        </p>
        <p>
            Praesent dictum eget magna sed volutpat. Sed ac leo ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nulla orci, viverra sit amet malesuada non, sodales euismod diam. Suspendisse potenti. Nullam porta mauris a rutrum hendrerit. Curabitur auctor fermentum lorem, vel malesuada enim ornare nec. Sed ornare sodales metus ut cursus.
        </p>
        <p>
            Maecenas a felis nisi. Sed accumsan ex tellus, et semper purus ultricies laoreet. Nulla posuere nisi vitae turpis varius, imperdiet ultrices turpis facilisis. Donec felis massa, laoreet sed neque id, malesuada convallis sapien. Nullam congue enim eget lacinia vulputate. Morbi accumsan augue vitae ex bibendum, id venenatis tortor venenatis. Nam nec venenatis elit, in viverra orci. In purus metus, iaculis quis turpis quis, pulvinar vehicula mauris. Etiam nulla leo, volutpat eu risus a, facilisis elementum massa. Phasellus id posuere augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent maximus dignissim vestibulum. Aliquam ullamcorper tellus eu quam posuere, sed dapibus erat commodo. Nullam elementum eu ante vel hendrerit. Aenean placerat lacus at lorem laoreet malesuada. Phasellus vitae leo id risus ultricies semper.
            Donec interdum ipsum diam, ut hendrerit mi vehicula non. Vivamus quam arcu, dignissim quis nisl non, vestibulum rutrum tellus. Quisque sed eros arcu. Aliquam viverra non enim et volutpat. Praesent neque mauris, blandit vitae libero et, fringilla finibus metus. Nunc interdum, tortor ut tempus hendrerit, libero elit convallis augue, sit amet viverra leo orci nec arcu. Morbi porttitor ligula est, id sagittis magna posuere at. Mauris aliquet turpis id diam rhoncus, quis euismod nulla vulputate. Fusce accumsan nunc purus, a rutrum purus rhoncus sed. Duis eu justo ornare, fermentum leo ut, rutrum mi. Nullam nec arcu vitae enim iaculis pulvinar in sit amet neque. In pretium lectus vel ipsum vehicula, in sodales purus viverra.
        </p>
        <p>
            Suspendisse potenti. Etiam at mattis urna. Vestibulum ut nulla leo. Donec pretium auctor euismod. Suspendisse tristique tortor non malesuada consequat. Nulla pellentesque eros mauris, non viverra mauris tempus nec. Cras id dapibus justo.
        </p>
        <p>
            Duis ut consequat mi, in bibendum lectus. Morbi cursus, risus vel aliquet sodales, velit nisi consequat nulla, nec faucibus nibh tellus at elit. Morbi commodo quam sapien, quis blandit diam aliquet eu. Phasellus nisl est, venenatis in nisl sit amet, commodo tempus velit. Maecenas at ipsum sodales, bibendum sem a, hendrerit orci. Cras viverra, dolor ac posuere auctor, nisl sapien commodo nunc, ac imperdiet nunc leo nec nunc. Nulla non dolor neque. Quisque sodales ipsum maximus mattis dapibus. Ut suscipit augue eget bibendum faucibus. Donec feugiat tempus suscipit. Donec eu justo odio. Vivamus vel nulla turpis. Aliquam eget justo magna. In sit amet dui id eros tincidunt sagittis ut in lorem. In pellentesque pharetra imperdiet.
        </p>
        <p>
            In hac habitasse platea dictumst. Praesent dictum eget magna sed volutpat. Sed ac leo ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec nulla orci, viverra sit amet malesuada non, sodales euismod diam. Suspendisse potenti. Nullam porta mauris a rutrum hendrerit. Curabitur auctor fermentum lorem, vel malesuada enim ornare nec. Sed ornare sodales metus ut cursus.
        </p>
        <p>
            Maecenas a felis nisi. Sed accumsan ex tellus, et semper purus ultricies laoreet. Nulla posuere nisi vitae turpis varius, imperdiet ultrices turpis facilisis. Donec felis massa, laoreet sed neque id, malesuada convallis sapien. Nullam congue enim eget lacinia vulputate. Morbi accumsan augue vitae ex bibendum, id venenatis tortor venenatis. Nam nec venenatis elit, in viverra orci. In purus metus, iaculis quis turpis quis, pulvinar vehicula mauris. Etiam nulla leo, volutpat eu risus a, facilisis elementum massa. Phasellus id posuere augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent maximus dignissim vestibulum. Aliquam ullamcorper tellus eu quam posuere, sed dapibus erat commodo. Nullam elementum eu ante vel hendrerit. Aenean placerat lacus at lorem laoreet malesuada. Phasellus vitae leo id risus ultricies semper.
            Donec interdum ipsum diam, ut hendrerit mi vehicula non. Vivamus quam arcu, dignissim quis nisl non, vestibulum rutrum tellus. Quisque sed eros arcu. Aliquam viverra non enim et volutpat. Praesent neque mauris, blandit vitae libero et, fringilla finibus metus. Nunc interdum, tortor ut tempus hendrerit, libero elit convallis augue, sit amet viverra leo orci nec arcu. Morbi porttitor ligula est, id sagittis magna posuere at. Mauris aliquet turpis id diam rhoncus, quis euismod nulla vulputate. Fusce accumsan nunc purus, a rutrum purus rhoncus sed. Duis eu justo ornare, fermentum leo ut, rutrum mi. Nullam nec arcu vitae enim iaculis pulvinar in sit amet neque. In pretium lectus vel ipsum vehicula, in sodales purus viverra.
        </p>
        <p>
            Suspendisse potenti. Etiam at mattis urna. Vestibulum ut nulla leo. Donec pretium auctor euismod. Suspendisse tristique tortor non malesuada consequat. Nulla pellentesque eros mauris, non viverra mauris tempus nec. Cras id dapibus justo.
        </p>
        <p>
            Suspendisse potenti. Etiam at mattis urna. Vestibulum ut nulla leo. Donec pretium auctor euismod. Suspendisse tristique tortor non malesuada consequat. Nulla pellentesque eros mauris, non viverra mauris tempus nec. Cras id dapibus justo.
        </p>
        <p>
            Duis ut consequat mi, in bibendum lectus. Morbi cursus, risus vel aliquet sodales, velit nisi consequat nulla, nec faucibus nibh tellus at elit. Morbi commodo quam sapien, quis blandit diam aliquet eu. Phasellus nisl est, venenatis in nisl sit amet, commodo tempus velit. Maecenas at ipsum sodales, bibendum sem a, hendrerit orci. Cras viverra, dolor ac posuere auctor, nisl sapien commodo nunc, ac imperdiet nunc leo nec nunc. Nulla non dolor neque. Quisque sodales ipsum maximus mattis dapibus. Ut suscipit augue eget bibendum faucibus. Donec feugiat tempus suscipit. Donec eu justo odio. Vivamus vel nulla turpis. Aliquam eget justo magna. In sit amet dui id eros tincidunt sagittis ut in lorem. In pellentesque pharetra imperdiet.
        </p>
        <p>
            Maecenas a felis nisi. Sed accumsan ex tellus, et semper purus ultricies laoreet. Nulla posuere nisi vitae turpis varius, imperdiet ultrices turpis facilisis. Donec felis massa, laoreet sed neque id, malesuada convallis sapien. Nullam congue enim eget lacinia vulputate. Morbi accumsan augue vitae ex bibendum, id venenatis tortor venenatis. Nam nec venenatis elit, in viverra orci. In purus metus, iaculis quis turpis quis, pulvinar vehicula mauris. Etiam nulla leo, volutpat eu risus a, facilisis elementum massa. Phasellus id posuere augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent maximus dignissim vestibulum. Aliquam ullamcorper tellus eu quam posuere, sed dapibus erat commodo. Nullam elementum eu ante vel hendrerit. Aenean placerat lacus at lorem laoreet malesuada. Phasellus vitae leo id risus ultricies semper.
            Donec interdum ipsum diam, ut hendrerit mi vehicula non. Vivamus quam arcu, dignissim quis nisl non, vestibulum rutrum tellus. Quisque sed eros arcu. Aliquam viverra non enim et volutpat. Praesent neque mauris, blandit vitae libero et, fringilla finibus metus. Nunc interdum, tortor ut tempus hendrerit, libero elit convallis augue, sit amet viverra leo orci nec arcu. Morbi porttitor ligula est, id sagittis magna posuere at. Mauris aliquet turpis id diam rhoncus, quis euismod nulla vulputate. Fusce accumsan nunc purus, a rutrum purus rhoncus sed. Duis eu justo ornare, fermentum leo ut, rutrum mi. Nullam nec arcu vitae enim iaculis pulvinar in sit amet neque. In pretium lectus vel ipsum vehicula, in sodales purus viverra.
        </p>

    </div>
  )
}
